import Foundation

public extension DeviceModel {
    enum IPadModel: String, Equatable, CaseIterable {
        // iPads
        case iPad1Wifi                      = "iPad1,1"
        case iPad1Celullar                  = "iPad1,2"
        case iPad2Wifi                      = "iPad2,1"
        case iPad2GSM                       = "iPad2,2"
        case iPad2CDMA                      = "iPad2,3"
        case iPad2NewRev                    = "iPad2,4"
        case iPad3Wifi                      = "iPad3,1"
        case iPad3CDMA                      = "iPad3,2"
        case iPad3GSM                       = "iPad3,3"
        case iPad4Wifi                      = "iPad3,4"
        case iPad4GSM                       = "iPad3,5"
        case iPad4CDMA                      = "iPad3,6"
        case iPad5Wifi                      = "iPad6,11"
        case iPad5Celullar                  = "iPad6,12"
        case iPad6Wifi                      = "iPad7,5"
        case iPad6Celullar                  = "iPad7,6"
        case iPad7Wifi                      = "iPad7,11"
        case iPad7Celullar                  = "iPad7,12"
        case iPad8Wifi                      = "iPad11,6"
        case iPad8Celullar                  = "iPad11,7"
        case iPad9Wifi                      = "iPad12,1"
        case iPad9Celullar                  = "iPad12,2"
        case iPad10Wifi                     = "iPad13,18"
        case iPad10Celullar                 = "iPad13,19"
        
        // Minis
        case iPadMini1Wifi                  = "iPad2,5"
        case iPadMini1GSM                   = "iPad2,6"
        case iPadMini1CDMA                  = "iPad2,7"
        case iPadMini2Wifi                  = "iPad4,4"
        case iPadMini2GSMCDMA               = "iPad4,5"
        case iPadMini2China                 = "iPad4,6"
        case iPadMini3Wifi                  = "iPad4,7"
        case iPadMini3GSMCDMA               = "iPad4,8"
        case iPadMini3China                 = "iPad4,9"
        case iPadMini4Wifi                  = "iPad5,1"
        case iPadMini4Celullar              = "iPad5,2"
        case iPadMini5Wifi                  = "iPad11,1"
        case iPadMini5Celullar              = "iPad11,2"
        case iPadMini6Wifi                  = "iPad14,1"
        case iPadMini6Celullar              = "iPad14,2"
        
        // Airs
        case iPadAir1Wifi                   = "iPad4,1"
        case iPadAir1GSMCDMA                = "iPad4,2"
        case iPadAir1China                  = "iPad4,3"
        case iPadAir2Wifi                   = "iPad5,3"
        case iPadAir2Celullar               = "iPad5,4"
        case iPadAir3Wifi                   = "iPad11,3"
        case iPadAir3Celullar               = "iPad11,4"
        case iPadAir4Wifi                   = "iPad13,1"
        case iPadAir4Celullar               = "iPad13,2"
        case iPadAir5Wifi                   = "iPad13,16"
        case iPadAir5Celullar               = "iPad13,17"
        
        // Pros
        case iPadPro1_9d7inchWifi           = "iPad6,3"
        case iPadPro1_9d7inchCelullar       = "iPad6,4"
        case iPadPro1_12d9inchWifi          = "iPad6,7"
        case iPadPro1_12d9inchCellular      = "iPad6,8"
        case iPadPro1_10d5inchWifi          = "iPad7,3"
        case iPadPro1_10d5inchCellular      = "iPad7,4"
        case iPadPro2_12d9inchWifi          = "iPad7,1"
        case iPadPro2_12d9inchCellular      = "iPad7,2"
        case iPadPro1_11inchWifi            = "iPad8,1"
        case iPadPro1_11inchWifiTera        = "iPad8,2"
        case iPadPro1_11inchCelullar        = "iPad8,3"
        case iPadPro1_11inchCelullarTera    = "iPad8,4"
        case iPadPro2_11inchWifi            = "iPad8,9"
        case iPadPro2_11inchCelullar        = "iPad8,10"
        case iPadPro3_12d9inchWifi          = "iPad8,5"
        case iPadPro3_12d9inchWifiTera      = "iPad8,6"
        case iPadPro3_12d9inchCellular      = "iPad8,7"
        case iPadPro3_12d9inchCellularTera  = "iPad8,8"
        case iPadPro4_12d9inchWifi          = "iPad8,11"
        case iPadPro4_12d9inchCellular      = "iPad8,12"
        case iPadPro3_11inchWifi            = "iPad13,4"
        case iPadPro3_11inchWifiTera        = "iPad13,5"
        case iPadPro3_11inchCellular        = "iPad13,6"
        case iPadPro3_11inchCellularTera    = "iPad13,7"
        case iPadPro5_12d9inchWifi          = "iPad13,8"
        case iPadPro5_12d9inchWifiTera      = "iPad13,9"
        case iPadPro5_12d9inchCellular      = "iPad13,10"
        case iPadPro5_12d9inchCellularTera  = "iPad13,11"
        case iPadPro4_11inchWifi            = "iPad14,3"
        case iPadPro4_11inchCellular        = "iPad14,4"
        case iPadPro6_12d9inchWifi          = "iPad14,5"
        case iPadPro6_12d9inchCellular      = "iPad14,6"
    }
}
