import Foundation

public extension DeviceModel {
    enum IPadModel: String, Equatable, CaseIterable {
        // iPads
        case gen1Wifi                   = "iPad1,1"
        case gen1Celullar               = "iPad1,2"
        case gen2Wifi                   = "iPad2,1"
        case gen2GSM                    = "iPad2,2"
        case gen2CDMA                   = "iPad2,3"
        case gen2NewRev                 = "iPad2,4"
        case gen3Wifi                   = "iPad3,1"
        case gen3CDMA                   = "iPad3,2"
        case gen3GSM                    = "iPad3,3"
        case gen4Wifi                   = "iPad3,4"
        case gen4GSM                    = "iPad3,5"
        case gen4CDMA                   = "iPad3,6"
        case gen5Wifi                   = "iPad6,11"
        case gen5Celullar               = "iPad6,12"
        case gen6Wifi                   = "iPad7,5"
        case gen6Celullar               = "iPad7,6"
        case gen7Wifi                   = "iPad7,11"
        case gen7Celullar               = "iPad7,12"
        case gen8Wifi                   = "iPad11,6"
        case gen8Celullar               = "iPad11,7"
        case gen9Wifi                   = "iPad12,1"
        case gen9Celullar               = "iPad12,2"
        case gen10Wifi                  = "iPad13,18"
        case gen10Celullar              = "iPad13,19"
        
        // Minis
        case mini1Wifi                  = "iPad2,5"
        case mini1GSM                   = "iPad2,6"
        case mini1CDMA                  = "iPad2,7"
        case mini2Wifi                  = "iPad4,4"
        case mini2GSMCDMA               = "iPad4,5"
        case mini2China                 = "iPad4,6"
        case mini3Wifi                  = "iPad4,7"
        case mini3GSMCDMA               = "iPad4,8"
        case mini3China                 = "iPad4,9"
        case mini4Wifi                  = "iPad5,1"
        case mini4Celullar              = "iPad5,2"
        case mini5Wifi                  = "iPad11,1"
        case mini5Celullar              = "iPad11,2"
        case mini6Wifi                  = "iPad14,1"
        case mini6Celullar              = "iPad14,2"
        
        // Airs
        case air1Wifi                   = "iPad4,1"
        case air1GSMCDMA                = "iPad4,2"
        case air1China                  = "iPad4,3"
        case air2Wifi                   = "iPad5,3"
        case air2Celullar               = "iPad5,4"
        case air3Wifi                   = "iPad11,3"
        case air3Celullar               = "iPad11,4"
        case air4Wifi                   = "iPad13,1"
        case air4Celullar               = "iPad13,2"
        case air5Wifi                   = "iPad13,16"
        case air5Celullar               = "iPad13,17"
        
        // Pros
        case pro1_9d7inchWifi           = "iPad6,3"
        case pro1_9d7inchCelullar       = "iPad6,4"
        case pro1_12d9inchWifi          = "iPad6,7"
        case pro1_12d9inchCellular      = "iPad6,8"
        case pro1_10d5inchWifi          = "iPad7,3"
        case pro1_10d5inchCellular      = "iPad7,4"
        case pro2_12d9inchWifi          = "iPad7,1"
        case pro2_12d9inchCellular      = "iPad7,2"
        case pro1_11inchWifi            = "iPad8,1"
        case pro1_11inchWifiTera        = "iPad8,2"
        case pro1_11inchCelullar        = "iPad8,3"
        case pro1_11inchCelullarTera    = "iPad8,4"
        case pro2_11inchWifi            = "iPad8,9"
        case pro2_11inchCelullar        = "iPad8,10"
        case pro3_12d9inchWifi          = "iPad8,5"
        case pro3_12d9inchWifiTera      = "iPad8,6"
        case pro3_12d9inchCellular      = "iPad8,7"
        case pro3_12d9inchCellularTera  = "iPad8,8"
        case pro4_12d9inchWifi          = "iPad8,11"
        case pro4_12d9inchCellular      = "iPad8,12"
        case pro3_11inchWifi            = "iPad13,4"
        case pro3_11inchWifiTera        = "iPad13,5"
        case pro3_11inchCellular        = "iPad13,6"
        case pro3_11inchCellularTera    = "iPad13,7"
        case pro5_12d9inchWifi          = "iPad13,8"
        case pro5_12d9inchWifiTera      = "iPad13,9"
        case pro5_12d9inchCellular      = "iPad13,10"
        case pro5_12d9inchCellularTera  = "iPad13,11"
        case pro4_11inchWifi            = "iPad14,3"
        case pro4_11inchCellular        = "iPad14,4"
        case pro6_12d9inchWifi          = "iPad14,5"
        case pro6_12d9inchCellular      = "iPad14,6"
    }
}
