import Foundation

public extension DeviceModel.IPadModel {
    var name: String {
        switch self {
        // iPads
        case .gen1Wifi:                     return "iPad 1G (Wifi)"
        case .gen1Celullar:                 return "iPad 1G (Celullar)"
        case .gen2Wifi:                     return "iPad 2G (Wifi)"
        case .gen2GSM:                      return "iPad 2G (GSM)"
        case .gen2CDMA:                     return "iPad 2G (CDMA)"
        case .gen2NewRev:                   return "iPad 2G (NewRev)"
        case .gen3Wifi:                     return "iPad 3G (Wifi)"
        case .gen3CDMA:                     return "iPad 3G (CDMA)"
        case .gen3GSM:                      return "iPad 3G (GSM)"
        case .gen4Wifi:                     return "iPad 4G (Wifi)"
        case .gen4GSM:                      return "iPad 4G (GSM)"
        case .gen4CDMA:                     return "iPad 4G (CDMA)"
        case .gen5Wifi:                     return "iPad 5G (Wifi)"
        case .gen5Celullar:                 return "iPad 5G (Celullar)"
        case .gen6Wifi:                     return "iPad 6G (Wifi)"
        case .gen6Celullar:                 return "iPad 6G (Celullar)"
        case .gen7Wifi:                     return "iPad 7G (Wifi)"
        case .gen7Celullar:                 return "iPad 7G (Celullar)"
        case .gen8Wifi:                     return "iPad 8G (Wifi)"
        case .gen8Celullar:                 return "iPad 8G (Celullar)"
        case .gen9Wifi:                     return "iPad 9G (Wifi)"
        case .gen9Celullar:                 return "iPad 9G (Celullar)"
        case .gen10Wifi:                    return "iPad 10G (Wifi)"
        case .gen10Celullar:                return "iPad 10G (Celullar)"
            
        // Minis
        case .mini1Wifi:                    return "iPad Mini 1 (Wifi)"
        case .mini1GSM:                     return "iPad Mini 1 (GSM)"
        case .mini1CDMA:                    return "iPad Mini 1 (CDMA)"
        case .mini2Wifi:                    return "iPad Mini 2 (Wifi)"
        case .mini2GSMCDMA:                 return "iPad Mini 2 (Celullar)"
        case .mini2China:                   return "iPad Mini 2 (China)"
        case .mini3Wifi:                    return "iPad Mini 3 (Wifi)"
        case .mini3GSMCDMA:                 return "iPad Mini 3 (Celullar)"
        case .mini3China:                   return "iPad Mini 3 (China)"
        case .mini4Wifi:                    return "iPad Mini 4 (Wifi)"
        case .mini4Celullar:                return "iPad Mini 4 (Celullar)"
        case .mini5Wifi:                    return "iPad Mini 5 (Wifi)"
        case .mini5Celullar:                return "iPad Mini 5 (Celullar)"
        case .mini6Wifi:                    return "iPad Mini 6 (Wifi)"
        case .mini6Celullar:                return "iPad Mini 6 (Celullar)"
            
        // Airs
        case .air1Wifi:                     return "iPad Air 1 (Wifi)"
        case .air1GSMCDMA:                  return "iPad Air 1 (Celullar)"
        case .air1China:                    return "iPad Air 1 (China)"
        case .air2Wifi:                     return "iPad Air 2 (Wifi)"
        case .air2Celullar:                 return "iPad Air 2 (Celullar)"
        case .air3Wifi:                     return "iPad Air 3 (Wifi)"
        case .air3Celullar:                 return "iPad Air 3 (Celullar)"
        case .air4Wifi:                     return "iPad Air 4 (Wifi)"
        case .air4Celullar:                 return "iPad Air 4 (Celullar)"
        case .air5Wifi:                     return "iPad Air 5 (Wifi)"
        case .air5Celullar:                 return "iPad Air 5 (Celullar)"
            
        // Pros
        case .pro1_9d7inchWifi:             return "iPad Pro 1G 9.7\" (Wifi)"
        case .pro1_9d7inchCelullar:         return "iPad Pro 1G 9.7\" (Celullar)"
        case .pro1_12d9inchWifi:            return "iPad Pro 1G 12.9\" (Wifi)"
        case .pro1_12d9inchCellular:        return "iPad Pro 1G 12.9\" (Celullar)"
        case .pro1_10d5inchWifi:            return "iPad Pro 1G 10.5\" (Wifi)"
        case .pro1_10d5inchCellular:        return "iPad Pro 1G 10.5\" (Celullar)"
        case .pro2_12d9inchWifi:            return "iPad Pro 2G 12.9\" (Wifi)"
        case .pro2_12d9inchCellular:        return "iPad Pro 2G 12.9\" (Celullar)"
        case .pro1_11inchWifi:              return "iPad Pro 1G 11\" (Wifi)"
        case .pro1_11inchWifiTera:          return "iPad Pro 1G 11\" (Wifi + Tera)"
        case .pro1_11inchCelullar:          return "iPad Pro 1G 11\" (Celullar)"
        case .pro1_11inchCelullarTera:      return "iPad Pro 1G 11\" (Celullar + Tera)"
        case .pro2_11inchWifi:              return "iPad Pro 2G 11\" (Wifi)"
        case .pro2_11inchCelullar:          return "iPad Pro 2G 11\" (Celullar)"
        case .pro3_12d9inchWifi:            return "iPad Pro 3G 12.9\" (Wifi)"
        case .pro3_12d9inchWifiTera:        return "iPad Pro 3G 12.9\" (Wifi + Tera)"
        case .pro3_12d9inchCellular:        return "iPad Pro 3G 12.9\" (Celullar)"
        case .pro3_12d9inchCellularTera:    return "iPad Pro 3G 12.9\" (Celullar + Tera)"
        case .pro4_12d9inchWifi:            return "iPad Pro 4G 12.9\" (Wifi)"
        case .pro4_12d9inchCellular:        return "iPad Pro 4G 12.9\" (Celullar)"
        case .pro3_11inchWifi:              return "iPad Pro 3G 11\" (Wifi)"
        case .pro3_11inchWifiTera:          return "iPad Pro 3G 11\" (Wifi + Tera)"
        case .pro3_11inchCellular:          return "iPad Pro 3G 11\" (Celullar)"
        case .pro3_11inchCellularTera:      return "iPad Pro 3G 11\" (Celullar + Tera)"
        case .pro5_12d9inchWifi:            return "iPad Pro 5G 12.9\" (Wifi)"
        case .pro5_12d9inchWifiTera:        return "iPad Pro 5G 12.9\" (Wifi + Tera)"
        case .pro5_12d9inchCellular:        return "iPad Pro 5G 12.9\" (Celullar)"
        case .pro5_12d9inchCellularTera:    return "iPad Pro 5G 12.9\" (Celullar + Tera)"
        case .pro4_11inchWifi:              return "iPad Pro 4G 11\" (Wifi)"
        case .pro4_11inchCellular:          return "iPad Pro 4G 11\" (Celullar)"
        case .pro6_12d9inchWifi:            return "iPad Pro 6G 12.9\" (Wifi)"
        case .pro6_12d9inchCellular:        return "iPad Pro 6G 12.9\" (Celullar)"
        }
    }
}
