import Foundation

public extension DeviceModel.IPhoneModel {
    var name: String {
        switch self {
        case .iPhone1G:             return "iPhone 1G"
        case .iPhone3G:             return "iPhone 3G"
        case .iPhone3GS:            return "iPhone 3GS"
        case .iPhone4GSM:           return "iPhone 4"
        case .iPhone4GSMRevA:       return "iPhone 4"
        case .iPhone4CDMA:          return "iPhone 4"
        case .iPhone4S:             return "iPhone 4S"
        case .iPhone5GSM:           return "iPhone 5"
        case .iPhone5Global:        return "iPhone 5"
        case .iPhone5CGSM:          return "iPhone 5C"
        case .iPhone5CGlobal:       return "iPhone 5C"
        case .iPhone5SGSM:          return "iPhone 5S"
        case .iPhone5SGlobal:       return "iPhone 5S"
        case .iPhone6:              return "iPhone 6"
        case .iPhone6Plus:          return "iPhone 6 Plus"
        case .iPhone6S:             return "iPhone 6S"
        case .iPhone6SPlus:         return "iPhone 6S Plus"
        case .iPhoneSE:             return "iPhone SE"
        case .iPhone7GSM:           return "iPhone 7"
        case .iPhone7Global:        return "iPhone 7"
        case .iPhone7PlusGSM:       return "iPhone 7 Plus"
        case .iPhone7PlusGlobal:    return "iPhone 7 Plus"
        case .iPhone8GSM:           return "iPhone 8"
        case .iPhone8Global:        return "iPhone 8"
        case .iPhone8PlusGSM:       return "iPhone 8 Plus"
        case .iPhone8PlusGlobal:    return "iPhone 8 Plus"
        case .iPhoneXGSM:           return "iPhone X"
        case .iPhoneXGlobal:        return "iPhone X"
        case .iPhoneXR:             return "iPhone XR"
        case .iPhoneXS:             return "iPhone XS"
        case .iPhoneXSMax:          return "iPhone XS Max"
        case .iPhone11:             return "iPhone 11"
        case .iPhone11Pro:          return "iPhone 11 Pro"
        case .iPhone11ProMax:       return "iPhone 11 Pro Max"
        case .iPhoneSE2G:           return "iPhone SE 2G"
        case .iPhone12Mini:         return "iPhone 12 Mini"
        case .iPhone12:             return "iPhone 12"
        case .iPhone12Pro:          return "iPhone 12 Pro"
        case .iPhone12ProMax:       return "iPhone 12 Pro Max"
        case .iPhone13Pro:          return "iPhone 13 Pro"
        case .iPhone13ProMax:       return "iPhone 13 Pro Max"
        case .iPhone13Mini:         return "iPhone 13 Mini"
        case .iPhone13:             return "iPhone 13"
        case .iPhoneSE3G:           return "iPhone SE 3G"
        case .iPhone14:             return "iPhone 14"
        case .iPhone14Plus:         return "iPhone 14 Plus"
        case .iPhone14Pro:          return "iPhone 14 Pro"
        case .iPhone14ProMax:       return "iPhone 14 Pro Max"
        case .iPhone15:             return "iPhone 15"
        case .iPhone15Plus:         return "iPhone 15 Plus"
        case .iPhone15Pro:          return "iPhone 15 Pro"
        case .iPhone15ProMax:       return "iPhone 15 Pro Max"
        }
    }
}
